name: 'Hello world docker'
description: 'Says hello'

inputs:
  who-to-greet:
    description: 'Name to greet'
    required: false
    default: 'World'

outputs:
  greeting:
    description: 'The greeting message'

runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
